# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

cache:
  packages: true
  
r_github_packages:
  # something wrong with Hmisc depedencies... 
  - cran/survival

repos:
  MRAN: "https://mran.microsoft.com/snapshot/2016-11-08"
  
warnings_are_errors: false
