# Sample .travis.yml for R projects from https://docs.travis-ci.com/user/languages/r/

language: r
sudo: required

# System dependencies for HTTP calling
apt_packages:
 - openjdk-7-jre

r_binary_packages:
 - dplyr
 - reshape2
 - tidyr
 - stringr
 - knitr

