# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

cache:
  directories: $TRAVIS_BUILD_DIR/packrat/
  packages: true

repos:
  MRAN: https://mran.microsoft.com/snapshot/2016-11-08
  
#install:
#   - R -e "0" --args --bootstrap-packrat

warnings_are_errors: false
